import enum

from .Ages import Age2AgeData


class UnitType:
    """How widely a unit is available, as the game's own tech tree classifies it."""

    unit = "Unit"                     # any civilisation may train it
    unit_upgrade = "UnitUpgrade"      # an upgraded tier of a generic line
    unique_unit = "UniqueUnit"        # one civilisation
    regional_unit = "RegionalUnit"    # a handful of civilisations


@enum.unique
class Age2UnitData(enum.IntEnum):

    def __new__(cls, id: int, *args, **kwargs):
        value = id
        obj = int.__new__(cls, value)
        obj._value_ = value
        return obj

    def __init__(
        self, id: int, location_name: str, unit_name: str, game_id: int,
        age: Age2AgeData, unit_type: UnitType, tier: int
    ) -> None:
        self.id = id
        self.location_name = location_name
        self.unit_name = unit_name
        self.game_id = game_id
        self.age = age
        self.unit_type = unit_type
        self.tier = tier
        # Bound by the modules in locations/connections/, which are imported for their side
        # effects: UnitLineUnits, UnitBuildings, UnitTechs, UnitVariants,
        # UnitUpgradeTokens. Declared here so
        # the attribute always exists; a missed binding would otherwise surface far from its
        # cause.
        self.line: 'Age2UnitLineData' = None
        self.buildings: list['Age2BuildingData'] = []
        self.upgrade_tech: 'Age2TechData' = None
        self.variant_game_ids: list[int] = []
        self.upgrade_tokens: list['Age2ItemData'] = []

    # 300 - 799 = Units. Ids are assigned in ascending game_id order.
    ARCHER                      = 300, "Own Archer", "Archer", 4, Age2AgeData.FEUDAL, UnitType.unit, 0
    HAND_CANNONEER              = 301, "Own Hand Cannoneer", "Hand Cannoneer", 5, Age2AgeData.IMPERIAL, UnitType.unit, 0
    ELITE_SKIRMISHER            = 302, "Own Elite Skirmisher", "Elite Skirmisher", 6, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    SKIRMISHER                  = 303, "Own Skirmisher", "Skirmisher", 7, Age2AgeData.FEUDAL, UnitType.unit, 0
    LONGBOWMAN                  = 304, "Own Longbowman", "Longbowman", 8, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    MANGUDAI                    = 305, "Own Mangudai", "Mangudai", 11, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    FISHING_SHIP                = 306, "Own Fishing Ship", "Fishing Ship", 13, Age2AgeData.DARK, UnitType.unit, 0
    TRADE_COG                   = 307, "Own Trade Cog", "Trade Cog", 17, Age2AgeData.FEUDAL, UnitType.unit, 0
    WAR_GALLEY                  = 308, "Own War Galley", "War Galley", 21, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    CROSSBOWMAN                 = 309, "Own Crossbowman", "Crossbowman", 24, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    TEUTONIC_KNIGHT             = 310, "Own Teutonic Knight", "Teutonic Knight", 25, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    BOMBARD_CANNON              = 311, "Own Bombard Cannon", "Bombard Cannon", 36, Age2AgeData.IMPERIAL, UnitType.unit, 0
    KNIGHT                      = 312, "Own Knight", "Knight", 38, Age2AgeData.CASTLE, UnitType.unit, 0
    CAVALRY_ARCHER              = 313, "Own Cavalry Archer", "Cavalry Archer", 39, Age2AgeData.CASTLE, UnitType.unit, 0
    CATAPHRACT                  = 314, "Own Cataphract", "Cataphract", 40, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    HUSKARL                     = 315, "Own Huskarl", "Huskarl", 41, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    JANISSARY                   = 316, "Own Janissary", "Janissary", 46, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    CHU_KO_NU                   = 317, "Own Chu Ko Nu", "Chu Ko Nu", 73, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    MILITIA                     = 318, "Own Militia", "Militia", 74, Age2AgeData.DARK, UnitType.unit, 0
    MAN_AT_ARMS                 = 319, "Own Man-at-Arms", "Man-at-Arms", 75, Age2AgeData.FEUDAL, UnitType.unit_upgrade, 1
    LONG_SWORDSMAN              = 320, "Own Long Swordsman", "Long Swordsman", 77, Age2AgeData.CASTLE, UnitType.unit_upgrade, 2
    VILLAGER_MALE               = 321, "Own Villager (Male)", "Villager (Male)", 83, Age2AgeData.DARK, UnitType.unit, 0
    SPEARMAN                    = 322, "Own Spearman", "Spearman", 93, Age2AgeData.FEUDAL, UnitType.unit, 0
    MONK                        = 323, "Own Monk", "Monk", 125, Age2AgeData.CASTLE, UnitType.unit, 0
    TRADE_CART            = 324, "Own Trade Cart", "Trade Cart", 128, Age2AgeData.FEUDAL, UnitType.unit, 0
    SLINGER                     = 325, "Own Slinger", "Slinger", 185, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    IMPERIAL_CAMEL_RIDER        = 326, "Own Imperial Camel Rider", "Imperial Camel Rider", 207, Age2AgeData.IMPERIAL, UnitType.unique_unit, 3
    WOAD_RAIDER                 = 327, "Own Woad Raider", "Woad Raider", 232, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    WAR_ELEPHANT                = 328, "Own War Elephant", "War Elephant", 239, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    LONGBOAT                    = 329, "Own Longboat", "Longboat", 250, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    SCORPION                    = 330, "Own Scorpion", "Scorpion", 279, Age2AgeData.CASTLE, UnitType.unit, 0
    MANGONEL                    = 331, "Own Mangonel", "Mangonel", 280, Age2AgeData.CASTLE, UnitType.unit, 0
    THROWING_AXEMAN             = 332, "Own Throwing Axeman", "Throwing Axeman", 281, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    MAMELUKE                    = 333, "Own Mameluke", "Mameluke", 282, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    CAVALIER                    = 334, "Own Cavalier", "Cavalier", 283, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    SAMURAI                     = 335, "Own Samurai", "Samurai", 291, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    VILLAGER_FEMALE             = 336, "Own Villager (Female)", "Villager (Female)", 293, Age2AgeData.DARK, UnitType.unit, 0
    CAMEL_RIDER                 = 337, "Own Camel Rider", "Camel Rider", 329, Age2AgeData.CASTLE, UnitType.regional_unit, 1
    HEAVY_CAMEL_RIDER           = 338, "Own Heavy Camel Rider", "Heavy Camel Rider", 330, Age2AgeData.IMPERIAL, UnitType.regional_unit, 2
    TREBUCHET_PACKED            = 339, "Own Trebuchet (Packed)", "Trebuchet (Packed)", 331, Age2AgeData.IMPERIAL, UnitType.unit, 0
    PIKEMAN                     = 340, "Own Pikeman", "Pikeman", 358, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    HALBERDIER                  = 341, "Own Halberdier", "Halberdier", 359, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 2
    CANNON_GALLEON              = 342, "Own Cannon Galleon", "Cannon Galleon", 420, Age2AgeData.IMPERIAL, UnitType.unit, 0
    CAPPED_RAM                  = 343, "Own Capped Ram", "Capped Ram", 422, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    PETARD                      = 344, "Own Petard", "Petard", 440, Age2AgeData.CASTLE, UnitType.unit, 0
    HUSSAR                      = 345, "Own Hussar", "Hussar", 441, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 2
    GALLEON                     = 346, "Own Galleon", "Galleon", 442, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 2
    SCOUT_CAVALRY               = 347, "Own Scout Cavalry", "Scout Cavalry", 448, Age2AgeData.FEUDAL, UnitType.unit, 0
    TWO_HANDED_SWORDSMAN        = 348, "Own Two Handed Swordsman", "Two Handed Swordsman", 473, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 3
    HEAVY_CAVALRY_ARCHER        = 349, "Own Heavy Cavalry Archer", "Heavy Cavalry Archer", 474, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    ARBALESTER                  = 350, "Own Arbalester", "Arbalester", 492, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 2
    DEMOLITION_SHIP             = 351, "Own Demolition Ship", "Demolition Ship", 527, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    HEAVY_DEMOLITION_SHIP       = 352, "Own Heavy Demolition Ship", "Heavy Demolition Ship", 528, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 2
    FIRE_SHIP                   = 353, "Own Fire Ship", "Fire Ship", 529, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    ELITE_LONGBOWMAN            = 354, "Own Elite Longbowman", "Elite Longbowman", 530, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ELITE_THROWING_AXEMAN       = 355, "Own Elite Throwing Axeman", "Elite Throwing Axeman", 531, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    FAST_FIRE_SHIP              = 356, "Own Fast Fire Ship", "Fast Fire Ship", 532, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 2
    ELITE_LONGBOAT              = 357, "Own Elite Longboat", "Elite Longboat", 533, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    ELITE_WOAD_RAIDER           = 358, "Own Elite Woad Raider", "Elite Woad Raider", 534, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    GALLEY                      = 359, "Own Galley", "Galley", 539, Age2AgeData.FEUDAL, UnitType.unit, 0
    HEAVY_SCORPION              = 360, "Own Heavy Scorpion", "Heavy Scorpion", 542, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    TRANSPORT_SHIP              = 361, "Own Transport Ship", "Transport Ship", 545, Age2AgeData.DARK, UnitType.unit, 0
    LIGHT_CAVALRY               = 362, "Own Light Cavalry", "Light Cavalry", 546, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    SIEGE_RAM                   = 363, "Own Siege Ram", "Siege Ram", 548, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 2
    ONAGER                      = 364, "Own Onager", "Onager", 550, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    ELITE_CATAPHRACT            = 365, "Own Elite Cataphract", "Elite Cataphract", 553, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ELITE_TEUTONIC_KNIGHT       = 366, "Own Elite Teutonic Knight", "Elite Teutonic Knight", 554, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ELITE_HUSKARL               = 367, "Own Elite Huskarl", "Elite Huskarl", 555, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ELITE_MAMELUKE              = 368, "Own Elite Mameluke", "Elite Mameluke", 556, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ELITE_JANISSARY             = 369, "Own Elite Janissary", "Elite Janissary", 557, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ELITE_WAR_ELEPHANT          = 370, "Own Elite War Elephant", "Elite War Elephant", 558, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ELITE_CHU_KO_NU             = 371, "Own Elite Chu Ko Nu", "Elite Chu Ko Nu", 559, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ELITE_SAMURAI               = 372, "Own Elite Samurai", "Elite Samurai", 560, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ELITE_MANGUDAI              = 373, "Own Elite Mangudai", "Elite Mangudai", 561, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    CHAMPION                    = 374, "Own Champion", "Champion", 567, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 4
    PALADIN                     = 375, "Own Paladin", "Paladin", 569, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 2
    SIEGE_ONAGER                = 376, "Own Siege Onager", "Siege Onager", 588, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 2
    JEAN_BUREAU                 = 377, "Own Jean Bureau", "Jean Bureau", 650, Age2AgeData.DARK, UnitType.unit, 0
    ELITE_CANNON_GALLEON        = 378, "Own Elite Cannon Galleon", "Elite Cannon Galleon", 691, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    BERSERK                     = 379, "Own Berserk", "Berserk", 692, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_BERSERK               = 380, "Own Elite Berserk", "Elite Berserk", 694, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    JAGUAR_WARRIOR              = 381, "Own Jaguar Warrior", "Jaguar Warrior", 725, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_JAGUAR_WARRIOR        = 382, "Own Elite Jaguar Warrior", "Elite Jaguar Warrior", 726, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    EAGLE_SCOUT                 = 383, "Own Eagle Scout", "Eagle Scout", 751, Age2AgeData.FEUDAL, UnitType.regional_unit, 0
    ELITE_EAGLE_WARRIOR         = 384, "Own Elite Eagle Warrior", "Elite Eagle Warrior", 752, Age2AgeData.IMPERIAL, UnitType.regional_unit, 2
    EAGLE_WARRIOR               = 385, "Own Eagle Warrior", "Eagle Warrior", 753, Age2AgeData.CASTLE, UnitType.regional_unit, 1
    TARKAN                      = 386, "Own Tarkan", "Tarkan", 755, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_TARKAN                = 387, "Own Elite Tarkan", "Elite Tarkan", 757, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    PLUMED_ARCHER               = 388, "Own Plumed Archer", "Plumed Archer", 763, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_PLUMED_ARCHER         = 389, "Own Elite Plumed Archer", "Elite Plumed Archer", 765, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    CONQUISTADOR                = 390, "Own Conquistador", "Conquistador", 771, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_CONQUISTADOR          = 391, "Own Elite Conquistador", "Elite Conquistador", 773, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    MISSIONARY                  = 392, "Own Missionary", "Missionary", 775, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    WAR_WAGON                   = 393, "Own War Wagon", "War Wagon", 827, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_WAR_WAGON             = 394, "Own Elite War Wagon", "Elite War Wagon", 829, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    TURTLE_SHIP                 = 395, "Own Turtle Ship", "Turtle Ship", 831, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_TURTLE_SHIP           = 396, "Own Elite Turtle Ship", "Elite Turtle Ship", 832, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    GENOESE_CROSSBOWMAN         = 397, "Own Genoese Crossbowman", "Genoese Crossbowman", 866, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_GENOESE_CROSSBOWMAN   = 398, "Own Elite Genoese Crossbowman", "Elite Genoese Crossbowman", 868, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    MAGYAR_HUSZAR               = 399, "Own Magyar Huszar", "Magyar Huszar", 869, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_MAGYAR_HUSZAR         = 400, "Own Elite Magyar Huszar", "Elite Magyar Huszar", 871, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ELEPHANT_ARCHER             = 401, "Own Elephant Archer", "Elephant Archer", 873, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    ELITE_ELEPHANT_ARCHER       = 402, "Own Elite Elephant Archer", "Elite Elephant Archer", 875, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    BOYAR                       = 403, "Own Boyar", "Boyar", 876, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_BOYAR                 = 404, "Own Elite Boyar", "Elite Boyar", 878, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    KAMAYUK                     = 405, "Own Kamayuk", "Kamayuk", 879, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_KAMAYUK               = 406, "Own Elite Kamayuk", "Elite Kamayuk", 881, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    CONDOTTIERO                 = 407, "Own Condottiero", "Condottiero", 882, Age2AgeData.IMPERIAL, UnitType.unique_unit, 0
    ORGAN_GUN                   = 408, "Own Organ Gun", "Organ Gun", 1001, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_ORGAN_GUN             = 409, "Own Elite Organ Gun", "Elite Organ Gun", 1003, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    CARAVEL                     = 410, "Own Caravel", "Caravel", 1004, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_CARAVEL               = 411, "Own Elite Caravel", "Elite Caravel", 1006, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    CAMEL_ARCHER                = 412, "Own Camel Archer", "Camel Archer", 1007, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_CAMEL_ARCHER          = 413, "Own Elite Camel Archer", "Elite Camel Archer", 1009, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    GENITOUR                    = 414, "Own Genitour", "Genitour", 1010, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_GENITOUR              = 415, "Own Elite Genitour", "Elite Genitour", 1012, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    GBETO                       = 416, "Own Gbeto", "Gbeto", 1013, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_GBETO                 = 417, "Own Elite Gbeto", "Elite Gbeto", 1015, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    SHOTEL_WARRIOR              = 418, "Own Shotel Warrior", "Shotel Warrior", 1016, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_SHOTEL_WARRIOR        = 419, "Own Elite Shotel Warrior", "Elite Shotel Warrior", 1018, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    FIRE_GALLEY                 = 420, "Own Fire Galley", "Fire Galley", 1103, Age2AgeData.FEUDAL, UnitType.unit, 0
    DEMOLITION_RAFT             = 421, "Own Demolition Raft", "Demolition Raft", 1104, Age2AgeData.FEUDAL, UnitType.unit, 0
    SIEGE_TOWER                 = 422, "Own Siege Tower", "Siege Tower", 1105, Age2AgeData.CASTLE, UnitType.unit, 0
    BALLISTA_ELEPHANT           = 423, "Own Ballista Elephant", "Ballista Elephant", 1120, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_BALLISTA_ELEPHANT     = 424, "Own Elite Ballista Elephant", "Elite Ballista Elephant", 1122, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    KARAMBIT_WARRIOR            = 425, "Own Karambit Warrior", "Karambit Warrior", 1123, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_KARAMBIT_WARRIOR      = 426, "Own Elite Karambit Warrior", "Elite Karambit Warrior", 1125, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ARAMBAI                     = 427, "Own Arambai", "Arambai", 1126, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_ARAMBAI               = 428, "Own Elite Arambai", "Elite Arambai", 1128, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    RATTAN_ARCHER               = 429, "Own Rattan Archer", "Rattan Archer", 1129, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_RATTAN_ARCHER         = 430, "Own Elite Rattan Archer", "Elite Rattan Archer", 1131, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    BATTLE_ELEPHANT             = 431, "Own Battle Elephant", "Battle Elephant", 1132, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    ELITE_BATTLE_ELEPHANT       = 432, "Own Elite Battle Elephant", "Elite Battle Elephant", 1134, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    IMPERIAL_SKIRMISHER         = 433, "Own Imperial Skirmisher", "Imperial Skirmisher", 1155, Age2AgeData.IMPERIAL, UnitType.unique_unit, 2
    KONNIK                      = 434, "Own Konnik", "Konnik", 1225, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_KONNIK                = 435, "Own Elite Konnik", "Elite Konnik", 1227, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    KESHIK                      = 436, "Own Keshik", "Keshik", 1228, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_KESHIK                = 437, "Own Elite Keshik", "Elite Keshik", 1230, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    KIPCHAK                     = 438, "Own Kipchak", "Kipchak", 1231, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_KIPCHAK               = 439, "Own Elite Kipchak", "Elite Kipchak", 1233, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    LEITIS                      = 440, "Own Leitis", "Leitis", 1234, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_LEITIS                = 441, "Own Elite Leitis", "Elite Leitis", 1236, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    BATTERING_RAM               = 442, "Own Battering Ram", "Battering Ram", 1258, Age2AgeData.CASTLE, UnitType.unit, 0
    FLAMING_CAMEL               = 443, "Own Flaming Camel", "Flaming Camel", 1263, Age2AgeData.IMPERIAL, UnitType.unique_unit, 0
    DRAGON_SHIP                 = 444, "Own Dragon Ship", "Dragon Ship", 1302, Age2AgeData.IMPERIAL, UnitType.unique_unit, 3
    STEPPE_LANCER               = 445, "Own Steppe Lancer", "Steppe Lancer", 1370, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    ELITE_STEPPE_LANCER         = 446, "Own Elite Steppe Lancer", "Elite Steppe Lancer", 1372, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    COUSTILLIER                 = 447, "Own Coustillier", "Coustillier", 1655, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_COUSTILLIER           = 448, "Own Elite Coustillier", "Elite Coustillier", 1657, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    SERJEANT                    = 449, "Own Serjeant", "Serjeant", 1658, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_SERJEANT              = 450, "Own Elite Serjeant", "Elite Serjeant", 1659, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    FLEMISH_MILITIA             = 451, "Own Flemish Militia", "Flemish Militia", 1699, Age2AgeData.FEUDAL, UnitType.unique_unit, 0
    OBUCH                       = 452, "Own Obuch", "Obuch", 1701, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_OBUCH                 = 453, "Own Elite Obuch", "Elite Obuch", 1703, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    HUSSITE_WAGON               = 454, "Own Hussite Wagon", "Hussite Wagon", 1704, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_HUSSITE_WAGON         = 455, "Own Elite Hussite Wagon", "Elite Hussite Wagon", 1706, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    WINGED_HUSSAR               = 456, "Own Winged Hussar", "Winged Hussar", 1707, Age2AgeData.IMPERIAL, UnitType.unique_unit, 3
    HOUFNICE                    = 457, "Own Houfnice", "Houfnice", 1709, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    URUMI_SWORDSMAN             = 458, "Own Urumi Swordsman", "Urumi Swordsman", 1735, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_URUMI_SWORDSMAN       = 459, "Own Elite Urumi Swordsman", "Elite Urumi Swordsman", 1737, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    CHAKRAM_THROWER             = 460, "Own Chakram Thrower", "Chakram Thrower", 1741, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_CHAKRAM_THROWER       = 461, "Own Elite Chakram Thrower", "Elite Chakram Thrower", 1743, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    ARMORED_ELEPHANT            = 462, "Own Armored Elephant", "Armored Elephant", 1744, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    SIEGE_ELEPHANT              = 463, "Own Siege Elephant", "Siege Elephant", 1746, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    GHULAM                      = 464, "Own Ghulam", "Ghulam", 1747, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_GHULAM                = 465, "Own Elite Ghulam", "Elite Ghulam", 1749, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    THIRISADAI                  = 466, "Own Thirisadai", "Thirisadai", 1750, Age2AgeData.IMPERIAL, UnitType.unique_unit, 0
    SHRIVAMSHA_RIDER            = 467, "Own Shrivamsha Rider", "Shrivamsha Rider", 1751, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_SHRIVAMSHA_RIDER      = 468, "Own Elite Shrivamsha Rider", "Elite Shrivamsha Rider", 1753, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    CAMEL_SCOUT                 = 469, "Own Camel Scout", "Camel Scout", 1755, Age2AgeData.FEUDAL, UnitType.unique_unit, 0
    RATHA                = 470, "Own Ratha", "Ratha", 1759, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_RATHA          = 471, "Own Elite Ratha", "Elite Ratha", 1761, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    CENTURION                   = 472, "Own Centurion", "Centurion", 1790, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_CENTURION             = 473, "Own Elite Centurion", "Elite Centurion", 1792, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    LEGIONARY                   = 474, "Own Legionary", "Legionary", 1793, Age2AgeData.IMPERIAL, UnitType.unique_unit, 3
    DROMON                      = 475, "Own Dromon", "Dromon", 1795, Age2AgeData.IMPERIAL, UnitType.regional_unit, 0
    COMPOSITE_BOWMAN            = 476, "Own Composite Bowman", "Composite Bowman", 1800, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_COMPOSITE_BOWMAN      = 477, "Own Elite Composite Bowman", "Elite Composite Bowman", 1802, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    MONASPA                     = 478, "Own Monaspa", "Monaspa", 1803, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_MONASPA               = 479, "Own Elite Monaspa", "Elite Monaspa", 1805, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    WARRIOR_PRIEST              = 480, "Own Warrior Priest", "Warrior Priest", 1811, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    SAVAR                       = 481, "Own Savar", "Savar", 1813, Age2AgeData.IMPERIAL, UnitType.unique_unit, 2
    FIRE_LANCER                 = 482, "Own Fire Lancer", "Fire Lancer", 1901, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    ELITE_FIRE_LANCER           = 483, "Own Elite Fire Lancer", "Elite Fire Lancer", 1903, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    ROCKET_CART                 = 484, "Own Rocket Cart", "Rocket Cart", 1904, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    HEAVY_ROCKET_CART           = 485, "Own Heavy Rocket Cart", "Heavy Rocket Cart", 1907, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    IRON_PAGODA                 = 486, "Own Iron Pagoda", "Iron Pagoda", 1908, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_IRON_PAGODA           = 487, "Own Elite Iron Pagoda", "Elite Iron Pagoda", 1910, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    GRENADIER                   = 488, "Own Grenadier", "Grenadier", 1911, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    LIAO_DAO                    = 489, "Own Liao Dao", "Liao Dao", 1920, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_LIAO_DAO              = 490, "Own Elite Liao Dao", "Elite Liao Dao", 1922, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    MOUNTED_TREBUCHET           = 491, "Own Mounted Trebuchet", "Mounted Trebuchet", 1923, Age2AgeData.IMPERIAL, UnitType.unique_unit, 0
    TRACTION_TREBUCHET          = 492, "Own Traction Trebuchet", "Traction Trebuchet", 1942, Age2AgeData.IMPERIAL, UnitType.regional_unit, 0
    HEI_GUANG_CAVALRY           = 493, "Own Hei Guang Cavalry", "Hei Guang Cavalry", 1944, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    HEAVY_HEI_GUANG_CAVALRY     = 494, "Own Heavy Hei Guang Cavalry", "Heavy Hei Guang Cavalry", 1946, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    LOU_CHUAN                   = 495, "Own Lou Chuan", "Lou Chuan", 1948, Age2AgeData.IMPERIAL, UnitType.regional_unit, 0
    TIGER_CAVALRY               = 496, "Own Tiger Cavalry", "Tiger Cavalry", 1949, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_TIGER_CAVALRY         = 497, "Own Elite Tiger Cavalry", "Elite Tiger Cavalry", 1951, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    XIANBEI_RAIDER              = 498, "Own Xianbei Raider", "Xianbei Raider", 1952, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    WHITE_FEATHER_GUARD         = 499, "Own White Feather Guard", "White Feather Guard", 1959, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_WHITE_FEATHER_GUARD   = 500, "Own Elite White Feather Guard", "Elite White Feather Guard", 1961, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    WAR_CHARIOT_FOCUS_FIRE      = 501, "Own War Chariot Focus Fire", "War Chariot Focus Fire", 1962, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    FIRE_ARCHER                 = 502, "Own Fire Archer", "Fire Archer", 1968, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_FIRE_ARCHER           = 503, "Own Elite Fire Archer", "Elite Fire Archer", 1970, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    JIAN_SWORDSMAN              = 504, "Own Jian Swordsman", "Jian Swordsman", 1974, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    WAR_CHARIOT_BARRAGE         = 505, "Own War Chariot Barrage", "War Chariot Barrage", 1980, Age2AgeData.CASTLE, UnitType.unit, 0
    IMMORTAL_MELEE              = 506, "Own Immortal Melee", "Immortal Melee", 2101, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_IMMORTAL_MELEE        = 507, "Own Elite Immortal Melee", "Elite Immortal Melee", 2102, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    STRATEGOS                   = 508, "Own Strategos", "Strategos", 2104, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_STRATEGOS             = 509, "Own Elite Strategos", "Elite Strategos", 2105, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    HIPPEUS                     = 510, "Own Hippeus", "Hippeus", 2107, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_HIPPEUS               = 511, "Own Elite Hippeus", "Elite Hippeus", 2108, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    HOPLITE                     = 512, "Own Hoplite", "Hoplite", 2110, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    ELITE_HOPLITE               = 513, "Own Elite Hoplite", "Elite Hoplite", 2111, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    LEMBOS                      = 514, "Own Lembos", "Lembos", 2123, Age2AgeData.DARK, UnitType.unit, 0
    WAR_LEMBOS                  = 515, "Own War Lembos", "War Lembos", 2124, Age2AgeData.FEUDAL, UnitType.unit_upgrade, 1
    HEAVY_LEMBOS                = 516, "Own Heavy Lembos", "Heavy Lembos", 2125, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    ELITE_LEMBOS                = 517, "Own Elite Lembos", "Elite Lembos", 2126, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    MONOREME                    = 518, "Own Monoreme", "Monoreme", 2127, Age2AgeData.FEUDAL, UnitType.unit, 0
    BIREME                      = 519, "Own Bireme", "Bireme", 2128, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    TRIREME                     = 520, "Own Trireme", "Trireme", 2129, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    GALLEY_ANTIQUITY            = 521, "Own Galley Antiquity", "Galley Antiquity", 2130, Age2AgeData.FEUDAL, UnitType.unit, 0
    WAR_GALLEY_ANTIQUITY        = 522, "Own War Galley Antiquity", "War Galley Antiquity", 2131, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    ELITE_GALLEY                = 523, "Own Elite Galley", "Elite Galley", 2132, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    INCENDIARY_RAFT             = 524, "Own Incendiary Raft", "Incendiary Raft", 2133, Age2AgeData.FEUDAL, UnitType.unit, 0
    INCENDIARY_SHIP             = 525, "Own Incendiary Ship", "Incendiary Ship", 2134, Age2AgeData.CASTLE, UnitType.unit_upgrade, 1
    HEAVY_INCENDIARY_SHIP       = 526, "Own Heavy Incendiary Ship", "Heavy Incendiary Ship", 2135, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    CATAPULT_SHIP               = 527, "Own Catapult Ship", "Catapult Ship", 2138, Age2AgeData.CASTLE, UnitType.unit, 0
    ONAGER_SHIP                 = 528, "Own Onager Ship", "Onager Ship", 2139, Age2AgeData.IMPERIAL, UnitType.unit_upgrade, 1
    LEVIATHAN                   = 529, "Own Leviathan", "Leviathan", 2140, Age2AgeData.IMPERIAL, UnitType.unit, 0
    TRANSPORT_SHIP_ANTIQUITY    = 530, "Own Transport Ship Antiquity", "Transport Ship Antiquity", 2148, Age2AgeData.DARK, UnitType.unit, 0
    MERCHANT_SHIP               = 531, "Own Merchant Ship", "Merchant Ship", 2149, Age2AgeData.FEUDAL, UnitType.unit, 0
    WAR_CHARIOT_ANTIQUITY       = 532, "Own War Chariot Antiquity", "War Chariot Antiquity", 2150, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    ELITE_WAR_CHARIOT_ANTIQUITY = 533, "Own Elite War Chariot Antiquity", "Elite War Chariot Antiquity", 2151, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    CHAMPI_SCOUT                = 534, "Own Champi Scout", "Champi Scout", 2550, Age2AgeData.DARK, UnitType.regional_unit, 0
    CHAMPI_WARRIOR              = 535, "Own Champi Warrior", "Champi Warrior", 2552, Age2AgeData.CASTLE, UnitType.regional_unit, 2
    ELITE_CHAMPI_WARRIOR        = 536, "Own Elite Champi Warrior", "Elite Champi Warrior", 2554, Age2AgeData.IMPERIAL, UnitType.regional_unit, 3
    GUECHA_WARRIOR              = 537, "Own Guecha Warrior", "Guecha Warrior", 2562, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_GUECHA_WARRIOR        = 538, "Own Elite Guecha Warrior", "Elite Guecha Warrior", 2564, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    KONA                        = 539, "Own Kona", "Kona", 2566, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_KONA                  = 540, "Own Elite Kona", "Elite Kona", 2568, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    BOLAS_RIDER                 = 541, "Own Bolas Rider", "Bolas Rider", 2569, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_BOLAS_RIDER           = 542, "Own Elite Bolas Rider", "Elite Bolas Rider", 2571, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    BLACKWOOD_ARCHER            = 543, "Own Blackwood Archer", "Blackwood Archer", 2579, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_BLACKWOOD_ARCHER      = 544, "Own Elite Blackwood Archer", "Elite Blackwood Archer", 2581, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    IBIRAPEMA_WARRIOR           = 545, "Own Ibirapema Warrior", "Ibirapema Warrior", 2582, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_IBIRAPEMA_WARRIOR     = 546, "Own Elite Ibirapema Warrior", "Elite Ibirapema Warrior", 2584, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    TEMPLE_GUARD                = 547, "Own Temple Guard", "Temple Guard", 2586, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    CHAMPI_RUNNER               = 548, "Own Champi Runner", "Champi Runner", 2588, Age2AgeData.FEUDAL, UnitType.regional_unit, 1
    CATAPULT_GALLEON            = 549, "Own Catapult Galleon", "Catapult Galleon", 2633, Age2AgeData.IMPERIAL, UnitType.regional_unit, 0
    MOUNTED_CROSSBOWMAN         = 550, "Own Mounted Crossbowman", "Mounted Crossbowman", 2700, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    HEAVY_MOUNTED_CROSSBOWMAN   = 551, "Own Heavy Mounted Crossbowman", "Heavy Mounted Crossbowman", 2701, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    VARANGIAN_GUARD             = 552, "Own Varangian Guard", "Varangian Guard", 2703, Age2AgeData.CASTLE, UnitType.regional_unit, 0
    ELITE_VARANGIAN_GUARD       = 553, "Own Elite Varangian Guard", "Elite Varangian Guard", 2704, Age2AgeData.IMPERIAL, UnitType.regional_unit, 1
    HEARTH_TROOP                = 554, "Own Hearth Troop", "Hearth Troop", 2705, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_HEARTH_TROOP          = 555, "Own Elite Hearth Troop", "Elite Hearth Troop", 2706, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    JARL                        = 556, "Own Jarl", "Jarl", 2708, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_JARL                  = 557, "Own Elite Jarl", "Elite Jarl", 2709, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1
    JOMSVIKING                  = 558, "Own Jomsviking", "Jomsviking", 2711, Age2AgeData.CASTLE, UnitType.unique_unit, 0
    ELITE_JOMSVIKING            = 559, "Own Elite Jomsviking", "Elite Jomsviking", 2712, Age2AgeData.IMPERIAL, UnitType.unique_unit, 1


NAME_TO_UNIT: dict[str, Age2UnitData] = {unit.unit_name: unit for unit in Age2UnitData}
GAME_ID_TO_UNIT: dict[int, Age2UnitData] = {unit.game_id: unit for unit in Age2UnitData}
