import enum

from .Ages import Age2AgeData


@enum.unique
class Age2UnitData(enum.IntEnum):

    def __new__(cls, id: int, *args, **kwargs):
        value = id
        obj = int.__new__(cls, value)
        obj._value_ = value
        return obj

    def __init__(
        self, id: int, location_name: str, unit_name: str, game_id: int,
        age: Age2AgeData, is_unique: bool, tier: int
    ) -> None:
        self.id = id
        self.location_name = location_name
        self.unit_name = unit_name
        self.game_id = game_id
        self.age = age
        self.is_unique = is_unique
        self.tier = tier
        # Bound by the modules in locations/connections/, which are imported for their side
        # effects: UnitLineUnits, UnitBuildings, UnitTechs, UnitVariants. Declared here so
        # the attribute always exists; a missed binding would otherwise surface far from its
        # cause.
        self.line: 'Age2UnitLineData' = None
        self.buildings: list['Age2BuildingData'] = []
        self.upgrade_tech: 'Age2TechData' = None
        self.variant_game_ids: list[int] = []

    # 300 - 999 = Units. Ids are assigned in ascending game_id order.
    ARCHER                      = 300, "Train Archer", "Archer", 4, Age2AgeData.FEUDAL, False, 0
    HAND_CANNONEER              = 301, "Train Hand Cannoneer", "Hand Cannoneer", 5, Age2AgeData.IMPERIAL, False, 0
    ELITE_SKIRMISHER            = 302, "Train Elite Skirmisher", "Elite Skirmisher", 6, Age2AgeData.CASTLE, False, 1
    SKIRMISHER                  = 303, "Train Skirmisher", "Skirmisher", 7, Age2AgeData.FEUDAL, False, 0
    LONGBOWMAN                  = 304, "Train Longbowman", "Longbowman", 8, Age2AgeData.CASTLE, True, 0
    MANGUDAI                    = 305, "Train Mangudai", "Mangudai", 11, Age2AgeData.CASTLE, True, 0
    FISHING_SHIP                = 306, "Train Fishing Ship", "Fishing Ship", 13, Age2AgeData.DARK, False, 0
    TRADE_COG                   = 307, "Train Trade Cog", "Trade Cog", 17, Age2AgeData.FEUDAL, False, 0
    WAR_GALLEY                  = 308, "Train War Galley", "War Galley", 21, Age2AgeData.CASTLE, False, 1
    CROSSBOWMAN                 = 309, "Train Crossbowman", "Crossbowman", 24, Age2AgeData.CASTLE, False, 1
    TEUTONIC_KNIGHT             = 310, "Train Teutonic Knight", "Teutonic Knight", 25, Age2AgeData.CASTLE, True, 0
    BOMBARD_CANNON              = 311, "Train Bombard Cannon", "Bombard Cannon", 36, Age2AgeData.IMPERIAL, False, 0
    KNIGHT                      = 312, "Train Knight", "Knight", 38, Age2AgeData.CASTLE, False, 0
    CAVALRY_ARCHER              = 313, "Train Cavalry Archer", "Cavalry Archer", 39, Age2AgeData.CASTLE, False, 0
    CATAPHRACT                  = 314, "Train Cataphract", "Cataphract", 40, Age2AgeData.CASTLE, True, 0
    HUSKARL                     = 315, "Train Huskarl", "Huskarl", 41, Age2AgeData.CASTLE, True, 0
    JANISSARY                   = 316, "Train Janissary", "Janissary", 46, Age2AgeData.CASTLE, True, 0
    CHU_KO_NU                   = 317, "Train Chu Ko Nu", "Chu Ko Nu", 73, Age2AgeData.CASTLE, True, 0
    MILITIA                     = 318, "Train Militia", "Militia", 74, Age2AgeData.DARK, False, 0
    MAN_AT_ARMS                 = 319, "Train Man-at-Arms", "Man-at-Arms", 75, Age2AgeData.FEUDAL, False, 1
    LONG_SWORDSMAN              = 320, "Train Long Swordsman", "Long Swordsman", 77, Age2AgeData.CASTLE, False, 2
    VILLAGER_MALE               = 321, "Train Villager (Male)", "Villager (Male)", 83, Age2AgeData.DARK, False, 0
    SPEARMAN                    = 322, "Train Spearman", "Spearman", 93, Age2AgeData.FEUDAL, False, 0
    MONK                        = 323, "Train Monk", "Monk", 125, Age2AgeData.CASTLE, False, 0
    TRADE_CART_EMPTY            = 324, "Train Trade Cart", "Trade Cart", 128, Age2AgeData.FEUDAL, False, 0
    SLINGER                     = 325, "Train Slinger", "Slinger", 185, Age2AgeData.CASTLE, False, 0
    IMPERIAL_CAMEL_RIDER        = 326, "Train Imperial Camel Rider", "Imperial Camel Rider", 207, Age2AgeData.IMPERIAL, False, 3
    WOAD_RAIDER                 = 327, "Train Woad Raider", "Woad Raider", 232, Age2AgeData.CASTLE, True, 0
    WAR_ELEPHANT                = 328, "Train War Elephant", "War Elephant", 239, Age2AgeData.CASTLE, True, 0
    LONGBOAT                    = 329, "Train Longboat", "Longboat", 250, Age2AgeData.CASTLE, False, 0
    SCORPION                    = 330, "Train Scorpion", "Scorpion", 279, Age2AgeData.CASTLE, False, 0
    MANGONEL                    = 331, "Train Mangonel", "Mangonel", 280, Age2AgeData.CASTLE, False, 0
    THROWING_AXEMAN             = 332, "Train Throwing Axeman", "Throwing Axeman", 281, Age2AgeData.CASTLE, True, 0
    MAMELUKE                    = 333, "Train Mameluke", "Mameluke", 282, Age2AgeData.CASTLE, True, 0
    CAVALIER                    = 334, "Train Cavalier", "Cavalier", 283, Age2AgeData.IMPERIAL, False, 1
    SAMURAI                     = 335, "Train Samurai", "Samurai", 291, Age2AgeData.CASTLE, True, 0
    VILLAGER_FEMALE             = 336, "Train Villager (Female)", "Villager (Female)", 293, Age2AgeData.DARK, False, 0
    CAMEL_RIDER                 = 337, "Train Camel Rider", "Camel Rider", 329, Age2AgeData.CASTLE, False, 1
    HEAVY_CAMEL_RIDER           = 338, "Train Heavy Camel Rider", "Heavy Camel Rider", 330, Age2AgeData.IMPERIAL, False, 2
    TREBUCHET_PACKED            = 339, "Train Trebuchet (Packed)", "Trebuchet (Packed)", 331, Age2AgeData.IMPERIAL, False, 0
    PIKEMAN                     = 340, "Train Pikeman", "Pikeman", 358, Age2AgeData.CASTLE, False, 1
    HALBERDIER                  = 341, "Train Halberdier", "Halberdier", 359, Age2AgeData.IMPERIAL, False, 2
    CANNON_GALLEON              = 342, "Train Cannon Galleon", "Cannon Galleon", 420, Age2AgeData.IMPERIAL, False, 0
    CAPPED_RAM                  = 343, "Train Capped Ram", "Capped Ram", 422, Age2AgeData.IMPERIAL, False, 1
    PETARD                      = 344, "Train Petard", "Petard", 440, Age2AgeData.CASTLE, False, 0
    HUSSAR                      = 345, "Train Hussar", "Hussar", 441, Age2AgeData.IMPERIAL, False, 2
    GALLEON                     = 346, "Train Galleon", "Galleon", 442, Age2AgeData.IMPERIAL, False, 2
    SCOUT_CAVALRY               = 347, "Train Scout Cavalry", "Scout Cavalry", 448, Age2AgeData.FEUDAL, False, 0
    TWO_HANDED_SWORDSMAN        = 348, "Train Two Handed Swordsman", "Two Handed Swordsman", 473, Age2AgeData.IMPERIAL, False, 3
    HEAVY_CAVALRY_ARCHER        = 349, "Train Heavy Cavalry Archer", "Heavy Cavalry Archer", 474, Age2AgeData.IMPERIAL, False, 1
    ARBALESTER                  = 350, "Train Arbalester", "Arbalester", 492, Age2AgeData.IMPERIAL, False, 2
    DEMOLITION_SHIP             = 351, "Train Demolition Ship", "Demolition Ship", 527, Age2AgeData.CASTLE, False, 1
    HEAVY_DEMOLITION_SHIP       = 352, "Train Heavy Demolition Ship", "Heavy Demolition Ship", 528, Age2AgeData.IMPERIAL, False, 2
    FIRE_SHIP                   = 353, "Train Fire Ship", "Fire Ship", 529, Age2AgeData.CASTLE, False, 1
    ELITE_LONGBOWMAN            = 354, "Train Elite Longbowman", "Elite Longbowman", 530, Age2AgeData.IMPERIAL, True, 1
    ELITE_THROWING_AXEMAN       = 355, "Train Elite Throwing Axeman", "Elite Throwing Axeman", 531, Age2AgeData.IMPERIAL, True, 1
    FAST_FIRE_SHIP              = 356, "Train Fast Fire Ship", "Fast Fire Ship", 532, Age2AgeData.IMPERIAL, False, 2
    ELITE_LONGBOAT              = 357, "Train Elite Longboat", "Elite Longboat", 533, Age2AgeData.IMPERIAL, False, 1
    ELITE_WOAD_RAIDER           = 358, "Train Elite Woad Raider", "Elite Woad Raider", 534, Age2AgeData.IMPERIAL, True, 1
    GALLEY                      = 359, "Train Galley", "Galley", 539, Age2AgeData.FEUDAL, False, 0
    HEAVY_SCORPION              = 360, "Train Heavy Scorpion", "Heavy Scorpion", 542, Age2AgeData.IMPERIAL, False, 1
    TRANSPORT_SHIP              = 361, "Train Transport Ship", "Transport Ship", 545, Age2AgeData.DARK, False, 0
    LIGHT_CAVALRY               = 362, "Train Light Cavalry", "Light Cavalry", 546, Age2AgeData.CASTLE, False, 1
    SIEGE_RAM                   = 363, "Train Siege Ram", "Siege Ram", 548, Age2AgeData.IMPERIAL, False, 2
    ONAGER                      = 364, "Train Onager", "Onager", 550, Age2AgeData.IMPERIAL, False, 1
    ELITE_CATAPHRACT            = 365, "Train Elite Cataphract", "Elite Cataphract", 553, Age2AgeData.IMPERIAL, True, 1
    ELITE_TEUTONIC_KNIGHT       = 366, "Train Elite Teutonic Knight", "Elite Teutonic Knight", 554, Age2AgeData.IMPERIAL, True, 1
    ELITE_HUSKARL               = 367, "Train Elite Huskarl", "Elite Huskarl", 555, Age2AgeData.IMPERIAL, True, 1
    ELITE_MAMELUKE              = 368, "Train Elite Mameluke", "Elite Mameluke", 556, Age2AgeData.IMPERIAL, True, 1
    ELITE_JANISSARY             = 369, "Train Elite Janissary", "Elite Janissary", 557, Age2AgeData.IMPERIAL, True, 1
    ELITE_WAR_ELEPHANT          = 370, "Train Elite War Elephant", "Elite War Elephant", 558, Age2AgeData.IMPERIAL, True, 1
    ELITE_CHU_KO_NU             = 371, "Train Elite Chu Ko Nu", "Elite Chu Ko Nu", 559, Age2AgeData.IMPERIAL, True, 1
    ELITE_SAMURAI               = 372, "Train Elite Samurai", "Elite Samurai", 560, Age2AgeData.IMPERIAL, True, 1
    ELITE_MANGUDAI              = 373, "Train Elite Mangudai", "Elite Mangudai", 561, Age2AgeData.IMPERIAL, True, 1
    CHAMPION                    = 374, "Train Champion", "Champion", 567, Age2AgeData.IMPERIAL, False, 4
    PALADIN                     = 375, "Train Paladin", "Paladin", 569, Age2AgeData.IMPERIAL, False, 2
    SIEGE_ONAGER                = 376, "Train Siege Onager", "Siege Onager", 588, Age2AgeData.IMPERIAL, False, 2
    JEAN_BUREAU                 = 377, "Train Jean Bureau", "Jean Bureau", 650, Age2AgeData.DARK, False, 0
    ELITE_CANNON_GALLEON        = 378, "Train Elite Cannon Galleon", "Elite Cannon Galleon", 691, Age2AgeData.IMPERIAL, False, 1
    BERSERK                     = 379, "Train Berserk", "Berserk", 692, Age2AgeData.CASTLE, True, 0
    ELITE_BERSERK               = 380, "Train Elite Berserk", "Elite Berserk", 694, Age2AgeData.IMPERIAL, True, 1
    JAGUAR_WARRIOR              = 381, "Train Jaguar Warrior", "Jaguar Warrior", 725, Age2AgeData.CASTLE, True, 0
    ELITE_JAGUAR_WARRIOR        = 382, "Train Elite Jaguar Warrior", "Elite Jaguar Warrior", 726, Age2AgeData.IMPERIAL, True, 1
    EAGLE_SCOUT                 = 383, "Train Eagle Scout", "Eagle Scout", 751, Age2AgeData.DARK, False, 0
    ELITE_EAGLE_WARRIOR         = 384, "Train Elite Eagle Warrior", "Elite Eagle Warrior", 752, Age2AgeData.IMPERIAL, False, 2
    EAGLE_WARRIOR               = 385, "Train Eagle Warrior", "Eagle Warrior", 753, Age2AgeData.CASTLE, False, 1
    TARKAN                      = 386, "Train Tarkan", "Tarkan", 755, Age2AgeData.CASTLE, True, 0
    ELITE_TARKAN                = 387, "Train Elite Tarkan", "Elite Tarkan", 757, Age2AgeData.IMPERIAL, True, 1
    PLUMED_ARCHER               = 388, "Train Plumed Archer", "Plumed Archer", 763, Age2AgeData.CASTLE, True, 0
    ELITE_PLUMED_ARCHER         = 389, "Train Elite Plumed Archer", "Elite Plumed Archer", 765, Age2AgeData.IMPERIAL, True, 1
    CONQUISTADOR                = 390, "Train Conquistador", "Conquistador", 771, Age2AgeData.CASTLE, True, 0
    ELITE_CONQUISTADOR          = 391, "Train Elite Conquistador", "Elite Conquistador", 773, Age2AgeData.IMPERIAL, True, 1
    MISSIONARY                  = 392, "Train Missionary", "Missionary", 775, Age2AgeData.CASTLE, False, 0
    WAR_WAGON                   = 393, "Train War Wagon", "War Wagon", 827, Age2AgeData.CASTLE, True, 0
    ELITE_WAR_WAGON             = 394, "Train Elite War Wagon", "Elite War Wagon", 829, Age2AgeData.IMPERIAL, True, 1
    TURTLE_SHIP                 = 395, "Train Turtle Ship", "Turtle Ship", 831, Age2AgeData.CASTLE, False, 0
    ELITE_TURTLE_SHIP           = 396, "Train Elite Turtle Ship", "Elite Turtle Ship", 832, Age2AgeData.IMPERIAL, False, 1
    GENOESE_CROSSBOWMAN         = 397, "Train Genoese Crossbowman", "Genoese Crossbowman", 866, Age2AgeData.CASTLE, True, 0
    ELITE_GENOESE_CROSSBOWMAN   = 398, "Train Elite Genoese Crossbowman", "Elite Genoese Crossbowman", 868, Age2AgeData.IMPERIAL, True, 1
    MAGYAR_HUSZAR               = 399, "Train Magyar Huszar", "Magyar Huszar", 869, Age2AgeData.CASTLE, True, 0
    ELITE_MAGYAR_HUSZAR         = 400, "Train Elite Magyar Huszar", "Elite Magyar Huszar", 871, Age2AgeData.IMPERIAL, True, 1
    ELEPHANT_ARCHER             = 401, "Train Elephant Archer", "Elephant Archer", 873, Age2AgeData.CASTLE, True, 0
    ELITE_ELEPHANT_ARCHER       = 402, "Train Elite Elephant Archer", "Elite Elephant Archer", 875, Age2AgeData.IMPERIAL, True, 1
    BOYAR                       = 403, "Train Boyar", "Boyar", 876, Age2AgeData.CASTLE, True, 0
    ELITE_BOYAR                 = 404, "Train Elite Boyar", "Elite Boyar", 878, Age2AgeData.IMPERIAL, True, 1
    KAMAYUK                     = 405, "Train Kamayuk", "Kamayuk", 879, Age2AgeData.IMPERIAL, True, 0
    ELITE_KAMAYUK               = 406, "Train Elite Kamayuk", "Elite Kamayuk", 881, Age2AgeData.IMPERIAL, True, 1
    CONDOTTIERO                 = 407, "Train Condottiero", "Condottiero", 882, Age2AgeData.IMPERIAL, False, 0
    ORGAN_GUN                   = 408, "Train Organ Gun", "Organ Gun", 1001, Age2AgeData.CASTLE, True, 0
    ELITE_ORGAN_GUN             = 409, "Train Elite Organ Gun", "Elite Organ Gun", 1003, Age2AgeData.IMPERIAL, True, 1
    CARAVEL                     = 410, "Train Caravel", "Caravel", 1004, Age2AgeData.CASTLE, False, 0
    ELITE_CARAVEL               = 411, "Train Elite Caravel", "Elite Caravel", 1006, Age2AgeData.IMPERIAL, False, 1
    CAMEL_ARCHER                = 412, "Train Camel Archer", "Camel Archer", 1007, Age2AgeData.CASTLE, True, 0
    ELITE_CAMEL_ARCHER          = 413, "Train Elite Camel Archer", "Elite Camel Archer", 1009, Age2AgeData.IMPERIAL, True, 1
    GENITOUR                    = 414, "Train Genitour", "Genitour", 1010, Age2AgeData.CASTLE, False, 0
    ELITE_GENITOUR              = 415, "Train Elite Genitour", "Elite Genitour", 1012, Age2AgeData.IMPERIAL, False, 1
    GBETO                       = 416, "Train Gbeto", "Gbeto", 1013, Age2AgeData.CASTLE, True, 0
    ELITE_GBETO                 = 417, "Train Elite Gbeto", "Elite Gbeto", 1015, Age2AgeData.IMPERIAL, True, 1
    SHOTEL_WARRIOR              = 418, "Train Shotel Warrior", "Shotel Warrior", 1016, Age2AgeData.CASTLE, True, 0
    ELITE_SHOTEL_WARRIOR        = 419, "Train Elite Shotel Warrior", "Elite Shotel Warrior", 1018, Age2AgeData.IMPERIAL, True, 1
    FIRE_GALLEY                 = 420, "Train Fire Galley", "Fire Galley", 1103, Age2AgeData.FEUDAL, False, 0
    DEMOLITION_RAFT             = 421, "Train Demolition Raft", "Demolition Raft", 1104, Age2AgeData.FEUDAL, False, 0
    SIEGE_TOWER                 = 422, "Train Siege Tower", "Siege Tower", 1105, Age2AgeData.CASTLE, False, 0
    BALLISTA_ELEPHANT           = 423, "Train Ballista Elephant", "Ballista Elephant", 1120, Age2AgeData.CASTLE, True, 0
    ELITE_BALLISTA_ELEPHANT     = 424, "Train Elite Ballista Elephant", "Elite Ballista Elephant", 1122, Age2AgeData.IMPERIAL, True, 1
    KARAMBIT_WARRIOR            = 425, "Train Karambit Warrior", "Karambit Warrior", 1123, Age2AgeData.CASTLE, True, 0
    ELITE_KARAMBIT_WARRIOR      = 426, "Train Elite Karambit Warrior", "Elite Karambit Warrior", 1125, Age2AgeData.IMPERIAL, True, 1
    ARAMBAI                     = 427, "Train Arambai", "Arambai", 1126, Age2AgeData.CASTLE, True, 0
    ELITE_ARAMBAI               = 428, "Train Elite Arambai", "Elite Arambai", 1128, Age2AgeData.IMPERIAL, True, 1
    RATTAN_ARCHER               = 429, "Train Rattan Archer", "Rattan Archer", 1129, Age2AgeData.CASTLE, True, 0
    ELITE_RATTAN_ARCHER         = 430, "Train Elite Rattan Archer", "Elite Rattan Archer", 1131, Age2AgeData.IMPERIAL, True, 1
    BATTLE_ELEPHANT             = 431, "Train Battle Elephant", "Battle Elephant", 1132, Age2AgeData.FEUDAL, False, 0
    ELITE_BATTLE_ELEPHANT       = 432, "Train Elite Battle Elephant", "Elite Battle Elephant", 1134, Age2AgeData.IMPERIAL, False, 1
    IMPERIAL_SKIRMISHER         = 433, "Train Imperial Skirmisher", "Imperial Skirmisher", 1155, Age2AgeData.IMPERIAL, False, 2
    KONNIK                      = 434, "Train Konnik", "Konnik", 1225, Age2AgeData.CASTLE, True, 0
    ELITE_KONNIK                = 435, "Train Elite Konnik", "Elite Konnik", 1227, Age2AgeData.IMPERIAL, True, 1
    KESHIK                      = 436, "Train Keshik", "Keshik", 1228, Age2AgeData.CASTLE, True, 0
    ELITE_KESHIK                = 437, "Train Elite Keshik", "Elite Keshik", 1230, Age2AgeData.IMPERIAL, True, 1
    KIPCHAK                     = 438, "Train Kipchak", "Kipchak", 1231, Age2AgeData.CASTLE, True, 0
    ELITE_KIPCHAK               = 439, "Train Elite Kipchak", "Elite Kipchak", 1233, Age2AgeData.IMPERIAL, True, 1
    LEITIS                      = 440, "Train Leitis", "Leitis", 1234, Age2AgeData.CASTLE, True, 0
    ELITE_LEITIS                = 441, "Train Elite Leitis", "Elite Leitis", 1236, Age2AgeData.IMPERIAL, True, 1
    BATTERING_RAM               = 442, "Train Battering Ram", "Battering Ram", 1258, Age2AgeData.CASTLE, False, 0
    FLAMING_CAMEL               = 443, "Train Flaming Camel", "Flaming Camel", 1263, Age2AgeData.IMPERIAL, True, 0
    DRAGON_SHIP                 = 444, "Train Dragon Ship", "Dragon Ship", 1302, Age2AgeData.IMPERIAL, False, 3
    STEPPE_LANCER               = 445, "Train Steppe Lancer", "Steppe Lancer", 1370, Age2AgeData.CASTLE, False, 0
    ELITE_STEPPE_LANCER         = 446, "Train Elite Steppe Lancer", "Elite Steppe Lancer", 1372, Age2AgeData.IMPERIAL, False, 1
    COUSTILLIER                 = 447, "Train Coustillier", "Coustillier", 1655, Age2AgeData.CASTLE, True, 0
    ELITE_COUSTILLIER           = 448, "Train Elite Coustillier", "Elite Coustillier", 1657, Age2AgeData.IMPERIAL, True, 1
    SERJEANT                    = 449, "Train Serjeant", "Serjeant", 1658, Age2AgeData.CASTLE, True, 0
    ELITE_SERJEANT              = 450, "Train Elite Serjeant", "Elite Serjeant", 1659, Age2AgeData.IMPERIAL, True, 1
    FLEMISH_MILITIA             = 451, "Train Flemish Militia", "Flemish Militia", 1699, Age2AgeData.IMPERIAL, False, 0
    OBUCH                       = 452, "Train Obuch", "Obuch", 1701, Age2AgeData.CASTLE, True, 0
    ELITE_OBUCH                 = 453, "Train Elite Obuch", "Elite Obuch", 1703, Age2AgeData.IMPERIAL, True, 1
    HUSSITE_WAGON               = 454, "Train Hussite Wagon", "Hussite Wagon", 1704, Age2AgeData.CASTLE, True, 0
    ELITE_HUSSITE_WAGON         = 455, "Train Elite Hussite Wagon", "Elite Hussite Wagon", 1706, Age2AgeData.IMPERIAL, True, 1
    WINGED_HUSSAR               = 456, "Train Winged Hussar", "Winged Hussar", 1707, Age2AgeData.IMPERIAL, False, 3
    HOUFNICE                    = 457, "Train Houfnice", "Houfnice", 1709, Age2AgeData.IMPERIAL, False, 1
    URUMI_SWORDSMAN             = 458, "Train Urumi Swordsman", "Urumi Swordsman", 1735, Age2AgeData.CASTLE, True, 0
    ELITE_URUMI_SWORDSMAN       = 459, "Train Elite Urumi Swordsman", "Elite Urumi Swordsman", 1737, Age2AgeData.IMPERIAL, True, 1
    CHAKRAM_THROWER             = 460, "Train Chakram Thrower", "Chakram Thrower", 1741, Age2AgeData.CASTLE, True, 0
    ELITE_CHAKRAM_THROWER       = 461, "Train Elite Chakram Thrower", "Elite Chakram Thrower", 1743, Age2AgeData.IMPERIAL, True, 1
    ARMORED_ELEPHANT            = 462, "Train Armored Elephant", "Armored Elephant", 1744, Age2AgeData.CASTLE, False, 0
    SIEGE_ELEPHANT              = 463, "Train Siege Elephant", "Siege Elephant", 1746, Age2AgeData.IMPERIAL, False, 1
    GHULAM                      = 464, "Train Ghulam", "Ghulam", 1747, Age2AgeData.CASTLE, True, 0
    ELITE_GHULAM                = 465, "Train Elite Ghulam", "Elite Ghulam", 1749, Age2AgeData.IMPERIAL, True, 1
    THIRISADAI                  = 466, "Train Thirisadai", "Thirisadai", 1750, Age2AgeData.DARK, False, 0
    SHRIVAMSHA_RIDER            = 467, "Train Shrivamsha Rider", "Shrivamsha Rider", 1751, Age2AgeData.FEUDAL, False, 0
    ELITE_SHRIVAMSHA_RIDER      = 468, "Train Elite Shrivamsha Rider", "Elite Shrivamsha Rider", 1753, Age2AgeData.IMPERIAL, False, 1
    CAMEL_SCOUT                 = 469, "Train Camel Scout", "Camel Scout", 1755, Age2AgeData.FEUDAL, False, 0
    RATHA_RANGED                = 470, "Train Ratha Ranged", "Ratha Ranged", 1759, Age2AgeData.CASTLE, True, 0
    ELITE_RATHA_RANGED          = 471, "Train Elite Ratha Ranged", "Elite Ratha Ranged", 1761, Age2AgeData.IMPERIAL, True, 1
    CENTURION                   = 472, "Train Centurion", "Centurion", 1790, Age2AgeData.CASTLE, True, 0
    ELITE_CENTURION             = 473, "Train Elite Centurion", "Elite Centurion", 1792, Age2AgeData.IMPERIAL, True, 1
    LEGIONARY                   = 474, "Train Legionary", "Legionary", 1793, Age2AgeData.IMPERIAL, False, 3
    DROMON                      = 475, "Train Dromon", "Dromon", 1795, Age2AgeData.DARK, False, 0
    COMPOSITE_BOWMAN            = 476, "Train Composite Bowman", "Composite Bowman", 1800, Age2AgeData.CASTLE, True, 0
    ELITE_COMPOSITE_BOWMAN      = 477, "Train Elite Composite Bowman", "Elite Composite Bowman", 1802, Age2AgeData.IMPERIAL, True, 1
    MONASPA                     = 478, "Train Monaspa", "Monaspa", 1803, Age2AgeData.CASTLE, True, 0
    ELITE_MONASPA               = 479, "Train Elite Monaspa", "Elite Monaspa", 1805, Age2AgeData.IMPERIAL, True, 1
    WARRIOR_PRIEST              = 480, "Train Warrior Priest", "Warrior Priest", 1811, Age2AgeData.CASTLE, False, 0
    SAVAR                       = 481, "Train Savar", "Savar", 1813, Age2AgeData.IMPERIAL, False, 2
    FIRE_LANCER                 = 482, "Train Fire Lancer", "Fire Lancer", 1901, Age2AgeData.DARK, False, 0
    ELITE_FIRE_LANCER           = 483, "Train Elite Fire Lancer", "Elite Fire Lancer", 1903, Age2AgeData.IMPERIAL, False, 1
    ROCKET_CART                 = 484, "Train Rocket Cart", "Rocket Cart", 1904, Age2AgeData.CASTLE, False, 0
    HEAVY_ROCKET_CART           = 485, "Train Heavy Rocket Cart", "Heavy Rocket Cart", 1907, Age2AgeData.IMPERIAL, False, 1
    IRON_PAGODA                 = 486, "Train Iron Pagoda", "Iron Pagoda", 1908, Age2AgeData.CASTLE, True, 0
    ELITE_IRON_PAGODA           = 487, "Train Elite Iron Pagoda", "Elite Iron Pagoda", 1910, Age2AgeData.IMPERIAL, True, 1
    GRENADIER                   = 488, "Train Grenadier", "Grenadier", 1911, Age2AgeData.FEUDAL, False, 0
    LIAO_DAO                    = 489, "Train Liao Dao", "Liao Dao", 1920, Age2AgeData.CASTLE, True, 0
    ELITE_LIAO_DAO              = 490, "Train Elite Liao Dao", "Elite Liao Dao", 1922, Age2AgeData.IMPERIAL, True, 1
    MOUNTED_TREBUCHET           = 491, "Train Mounted Trebuchet", "Mounted Trebuchet", 1923, Age2AgeData.CASTLE, False, 0
    TRACTION_TREBUCHET          = 492, "Train Traction Trebuchet", "Traction Trebuchet", 1942, Age2AgeData.CASTLE, False, 0
    HEI_GUANG_CAVALRY           = 493, "Train Hei Guang Cavalry", "Hei Guang Cavalry", 1944, Age2AgeData.FEUDAL, False, 0
    HEAVY_HEI_GUANG_CAVALRY     = 494, "Train Heavy Hei Guang Cavalry", "Heavy Hei Guang Cavalry", 1946, Age2AgeData.IMPERIAL, False, 1
    LOU_CHUAN                   = 495, "Train Lou Chuan", "Lou Chuan", 1948, Age2AgeData.DARK, False, 0
    TIGER_CAVALRY               = 496, "Train Tiger Cavalry", "Tiger Cavalry", 1949, Age2AgeData.CASTLE, True, 0
    ELITE_TIGER_CAVALRY         = 497, "Train Elite Tiger Cavalry", "Elite Tiger Cavalry", 1951, Age2AgeData.IMPERIAL, True, 1
    XIANBEI_RAIDER              = 498, "Train Xianbei Raider", "Xianbei Raider", 1952, Age2AgeData.FEUDAL, False, 0
    WHITE_FEATHER_GUARD         = 499, "Train White Feather Guard", "White Feather Guard", 1959, Age2AgeData.CASTLE, True, 0
    ELITE_WHITE_FEATHER_GUARD   = 500, "Train Elite White Feather Guard", "Elite White Feather Guard", 1961, Age2AgeData.IMPERIAL, True, 1
    WAR_CHARIOT_FOCUS_FIRE      = 501, "Train War Chariot Focus Fire", "War Chariot Focus Fire", 1962, Age2AgeData.CASTLE, False, 0
    FIRE_ARCHER                 = 502, "Train Fire Archer", "Fire Archer", 1968, Age2AgeData.CASTLE, True, 0
    ELITE_FIRE_ARCHER           = 503, "Train Elite Fire Archer", "Elite Fire Archer", 1970, Age2AgeData.IMPERIAL, True, 1
    JIAN_SWORDSMAN              = 504, "Train Jian Swordsman", "Jian Swordsman", 1974, Age2AgeData.DARK, False, 0
    WAR_CHARIOT_BARRAGE         = 505, "Train War Chariot Barrage", "War Chariot Barrage", 1980, Age2AgeData.CASTLE, False, 0
    IMMORTAL_MELEE              = 506, "Train Immortal Melee", "Immortal Melee", 2101, Age2AgeData.CASTLE, True, 0
    ELITE_IMMORTAL_MELEE        = 507, "Train Elite Immortal Melee", "Elite Immortal Melee", 2102, Age2AgeData.IMPERIAL, True, 1
    STRATEGOS                   = 508, "Train Strategos", "Strategos", 2104, Age2AgeData.CASTLE, True, 0
    ELITE_STRATEGOS             = 509, "Train Elite Strategos", "Elite Strategos", 2105, Age2AgeData.IMPERIAL, True, 1
    HIPPEUS                     = 510, "Train Hippeus", "Hippeus", 2107, Age2AgeData.CASTLE, True, 0
    ELITE_HIPPEUS               = 511, "Train Elite Hippeus", "Elite Hippeus", 2108, Age2AgeData.IMPERIAL, True, 1
    HOPLITE                     = 512, "Train Hoplite", "Hoplite", 2110, Age2AgeData.DARK, False, 0
    ELITE_HOPLITE               = 513, "Train Elite Hoplite", "Elite Hoplite", 2111, Age2AgeData.IMPERIAL, False, 1
    LEMBOS                      = 514, "Train Lembos", "Lembos", 2123, Age2AgeData.DARK, False, 0
    WAR_LEMBOS                  = 515, "Train War Lembos", "War Lembos", 2124, Age2AgeData.FEUDAL, False, 1
    HEAVY_LEMBOS                = 516, "Train Heavy Lembos", "Heavy Lembos", 2125, Age2AgeData.CASTLE, False, 1
    ELITE_LEMBOS                = 517, "Train Elite Lembos", "Elite Lembos", 2126, Age2AgeData.IMPERIAL, False, 1
    MONOREME                    = 518, "Train Monoreme", "Monoreme", 2127, Age2AgeData.DARK, False, 0
    BIREME                      = 519, "Train Bireme", "Bireme", 2128, Age2AgeData.CASTLE, False, 1
    TRIREME                     = 520, "Train Trireme", "Trireme", 2129, Age2AgeData.IMPERIAL, False, 1
    GALLEY_ANTIQUITY            = 521, "Train Galley Antiquity", "Galley Antiquity", 2130, Age2AgeData.DARK, False, 0
    WAR_GALLEY_ANTIQUITY        = 522, "Train War Galley Antiquity", "War Galley Antiquity", 2131, Age2AgeData.CASTLE, False, 1
    ELITE_GALLEY                = 523, "Train Elite Galley", "Elite Galley", 2132, Age2AgeData.IMPERIAL, False, 1
    INCENDIARY_RAFT             = 524, "Train Incendiary Raft", "Incendiary Raft", 2133, Age2AgeData.DARK, False, 0
    INCENDIARY_SHIP             = 525, "Train Incendiary Ship", "Incendiary Ship", 2134, Age2AgeData.CASTLE, False, 1
    HEAVY_INCENDIARY_SHIP       = 526, "Train Heavy Incendiary Ship", "Heavy Incendiary Ship", 2135, Age2AgeData.IMPERIAL, False, 1
    CATAPULT_SHIP               = 527, "Train Catapult Ship", "Catapult Ship", 2138, Age2AgeData.DARK, False, 0
    ONAGER_SHIP                 = 528, "Train Onager Ship", "Onager Ship", 2139, Age2AgeData.IMPERIAL, False, 1
    LEVIATHAN                   = 529, "Train Leviathan", "Leviathan", 2140, Age2AgeData.DARK, False, 0
    TRANSPORT_SHIP_ANTIQUITY    = 530, "Train Transport Ship Antiquity", "Transport Ship Antiquity", 2148, Age2AgeData.DARK, False, 0
    MERCHANT_SHIP               = 531, "Train Merchant Ship", "Merchant Ship", 2149, Age2AgeData.DARK, False, 0
    WAR_CHARIOT_ANTIQUITY       = 532, "Train War Chariot Antiquity", "War Chariot Antiquity", 2150, Age2AgeData.FEUDAL, False, 0
    ELITE_WAR_CHARIOT_ANTIQUITY = 533, "Train Elite War Chariot Antiquity", "Elite War Chariot Antiquity", 2151, Age2AgeData.IMPERIAL, False, 1
    UNIT_2550                   = 534, "Train Unit 2550", "Unit 2550", 2550, Age2AgeData.DARK, False, 0
    UNIT_2552                   = 535, "Train Unit 2552", "Unit 2552", 2552, Age2AgeData.CASTLE, False, 2
    UNIT_2554                   = 536, "Train Unit 2554", "Unit 2554", 2554, Age2AgeData.IMPERIAL, False, 3
    UNIT_2562                   = 537, "Train Unit 2562", "Unit 2562", 2562, Age2AgeData.CASTLE, True, 0
    UNIT_2564                   = 538, "Train Unit 2564", "Unit 2564", 2564, Age2AgeData.IMPERIAL, True, 1
    UNIT_2566                   = 539, "Train Unit 2566", "Unit 2566", 2566, Age2AgeData.CASTLE, True, 0
    UNIT_2568                   = 540, "Train Unit 2568", "Unit 2568", 2568, Age2AgeData.IMPERIAL, True, 1
    UNIT_2569                   = 541, "Train Unit 2569", "Unit 2569", 2569, Age2AgeData.FEUDAL, False, 0
    UNIT_2571                   = 542, "Train Unit 2571", "Unit 2571", 2571, Age2AgeData.IMPERIAL, False, 1
    UNIT_2579                   = 543, "Train Unit 2579", "Unit 2579", 2579, Age2AgeData.CASTLE, True, 0
    UNIT_2581                   = 544, "Train Unit 2581", "Unit 2581", 2581, Age2AgeData.IMPERIAL, True, 1
    UNIT_2582                   = 545, "Train Unit 2582", "Unit 2582", 2582, Age2AgeData.DARK, False, 0
    UNIT_2584                   = 546, "Train Unit 2584", "Unit 2584", 2584, Age2AgeData.IMPERIAL, False, 1
    UNIT_2586                   = 547, "Train Unit 2586", "Unit 2586", 2586, Age2AgeData.DARK, False, 0
    UNIT_2588                   = 548, "Train Unit 2588", "Unit 2588", 2588, Age2AgeData.FEUDAL, False, 1


NAME_TO_UNIT: dict[str, Age2UnitData] = {unit.unit_name: unit for unit in Age2UnitData}
GAME_ID_TO_UNIT: dict[int, Age2UnitData] = {unit.game_id: unit for unit in Age2UnitData}
